### ISSUE TITLE
Updated igmguesses does not work

### ISSUE THREAD

**Issue by marijana777** [pyigm/pyigm#118]
pyigm_igmguesses spectrum_file.fits   gives an error:
Traceback (most recent call last):
  File "/home/user/anaconda3/bin/pyigm_igmguesses", line 11, in <module>
    load_entry_point('pyigm', 'console_scripts', 'pyigm_igmguesses')()
  File "/home/user/pyigm/pyigm/scripts/pyigm_igmguesses.py", line 76, in main
    external_model=pargs.external_model)
  File "/home/user/pyigm/pyigm/guis/igmguesses.py", line 274, in __init__
    self.meta = fill_meta(self.meta)
  File "/home/user/pyigm/pyigm/guis/igmguesses.py", line 2008, in fill_meta
    radec = raw_input("Please provide (RA,DEC) J2000 in degrees (e.g. 123.45678,-87.6543): ")
NameError: name 'raw_input' is not defined

**Comment by profxj** [comment]
1.  Your title is not specific enough
2.  Did you Google "Python raw_input NameError"?  If not, what did you Google?
3.  This is a trivial fix. Please make it.

**Comment by ntejos** [comment]
Thanks for the issue. This will be (hopefully) addressed in PR #120 .

**Comment by profxj** [comment]
@marijana777 -- Is this still a problem?  If not, please close it.

**Comment by marijana777** [comment]
Closing it.
