### ISSUE TITLE
Igmguesses error "Input reliability not valid."

### ISSUE THREAD

**Issue by marijana777** [pyigm/pyigm#119]
Version 8f4acf1: 
For a number of files pyigm_igmguesses spectrum_file.fits -p json_file.json -o new_json_file.json gives an error which is copied below.
Previous version that I was using was working properly on all files (it should be before updating PyQT5).

Traceback (most recent call last):
  File "/home/user/pyigm/pyigm/guis/igmguesses.py", line 423, in read_previous
    chk_sep=False, chk_data=False, chk_vel=False)
  File "/home/user/linetools/linetools/isgm/abscomponent.py", line 156, in from_dict
    comment=idict['comment'], name=idict['Name'], reliability=reliability)
  File "/home/user/linetools/linetools/isgm/abscomponent.py", line 243, in __init__
    raise ValueError("Input reliability not valid.")
ValueError: Input reliability not valid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/bin/pyigm_igmguesses", line 11, in <module>
    load_entry_point('pyigm', 'console_scripts', 'pyigm_igmguesses')()
  File "/home/user/pyigm/pyigm/scripts/pyigm_igmguesses.py", line 76, in main
    external_model=pargs.external_model)
  File "/home/user/pyigm/pyigm/guis/igmguesses.py", line 268, in __init__
    self.read_previous()
  File "/home/user/pyigm/pyigm/guis/igmguesses.py", line 426, in read_previous
    chk_sep=False, chk_data=False, chk_vel=False)
  File "/home/user/linetools/linetools/isgm/abscomponent.py", line 156, in from_dict
    comment=idict['comment'], name=idict['Name'], reliability=reliability)
  File "/home/user/linetools/linetools/isgm/abscomponent.py", line 243, in __init__
    raise ValueError("Input reliability not valid.")
ValueError: Input reliability not valid.

**Comment by marijana777** [comment]
It can be solved by opening json_file.json, and replacing "Reliability": "None" with any "a", "b", "c".

**Comment by ntejos** [comment]
In the more general context, if you do not know the reliability of your component, you should have replaced "None" with "none" instead. @marijana777
