### ISSUE TITLE
A Problem with my backend? 

### ISSUE THREAD

**Issue by jessicawerk** [pyigm/pyigm#191]
I am trying to get up to date version of pyigm_igmgueses GUI running on my mac desktop (El Capitan, if that's relevant), but it is broken for a very irritating reason, some kind of weird mismatch between pyqt4 and pyqt5? 
So, I have updated linetools, pyigm, astropy, etc., and am using pyqt5 in general (though I tried to switch to pyqt4 and it did NOT solve the problem). Anyway, when I try to run the GUI, I get the following message: 
 - pyigm_igmguesses J1616+4154_nbin3_jwnorm.fits
Traceback (most recent call last):
  File "/Users/jwerk/anaconda/bin/pyigm_igmguesses", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/jwerk/python/pyigm/bin/pyigm_igmguesses", line 16, in <module>
    pyigm_igmguesses.main(args)
  File "/Users/jwerk/python/pyigm/pyigm/scripts/pyigm_igmguesses.py", line 53, in main
    from pyigm.guis.igmguesses import IGMGuessesGui
  File "/Users/jwerk/python/pyigm/pyigm/guis/igmguesses.py", line 33, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 18, in <module>
    from .backend_qt5 import QtCore
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4

When I switch to pyqt4, it just tells me there is no module named pyqt5. I feel like this has something to do with matplotlibrc, but my backend seems to be tkAgg as recommended...? Though I am not sure how to test beyond looking into .matplotlibrc/matplotlibrc file. 

Thanks a ton in advance if you have any advice on this. It runs fine on my laptop, but there is something weird happening on my desktop: 

python --version
Python 2.7.11 :: Anaconda custom (x86_64)

Thanks!

**Comment by jessicawerk** [comment]
Also, I will add, it's not just IGMguesses GUI. lt_continuum fit is broken with the same error too (see below). This is definitely some larger issue, and sorry to bother you with it. I've burned a couple hours already playing around with backends to no avail, and am just hoping one of you has some insight into this weird error. Otherwise, I'll just be rebuilding python entirely on my desktop from scratch (and probably switching to python 3). Thanks. 


lt_continuumfit --redshift 0.440 J1616+4154_nbin3_coadd.fits J1616+4154_nbin3_test.fits
Traceback (most recent call last):
  File "/Users/jwerk/anaconda/bin/lt_continuumfit", line 9, in <module>
    load_entry_point('linetools', 'console_scripts', 'lt_continuumfit')()
  File "/Users/jwerk/python/linetools/linetools/scripts/lt_continuumfit.py", line 27, in main
    from linetools.guis.xspecgui import XSpecGui
  File "/Users/jwerk/python/linetools/linetools/guis/xspecgui.py", line 20, in <module>
    from linetools.guis import spec_widgets as ltgsp
  File "/Users/jwerk/python/linetools/linetools/guis/spec_widgets.py", line 20, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 18, in <module>
    from .backend_qt5 import QtCore
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 91, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4

**Comment by jessicawerk** [comment]
Also, as for my current backend, it is Tkagg: 
>>> import matplotlib
>>> matplotlib.get_backend()
u'TkAgg'
>>> print (matplotlib.rcParams['backend']) 
TkAgg
I'm not sure what that "u" is being printed at all...?

**Comment by jessicawerk** [comment]
Well, I have temporarily solved the issue by setting: 
backend      : Qt5Agg
in the matplotlibrc file in the .matplotlib directory. Both GUIs are working again. Slightly concerned I will break something else doing this... but for now, all is well. Let me know if you have any thoughts!

**Comment by profxj** [comment]
This is the correct solution, as I understand it.

And yes, it is time to move to Python 3.
