### ISSUE TITLE
output json files from different versions of igmguesses leading to a code crash

### ISSUE THREAD

**Issue by jessicawerk** [pyigm/pyigm#212]
My student Hannah is working on some Keck HIRES spectra, and analyzing them with an MCMC fitter she developed and she has run into a problem with py_igmguesses output files. She wrote a set of codes to read in .json files output by igmguesses and use those b, v, N values as “initial guesses” for her MCMC profile fitter. It used to work on old json files from earlier igmguesses versions, but no longer works on current json output files. I am pasting the error here: 

Traceback (most recent call last):
  File "mcmc_wrapper_manual.py", line 121, in <module>
    run_mcmc_fitter_candy_manual.run_all(inputfits,inputjson,outtxt,z_component,species,BHB)
  File "/Users/hannahbish/Dropbox/BHB_MCMC/Hannah_test/run_mcmc_fitter_candy_manual.py", line 131, in run_all
    data['wave_b'], data['wave_r'])
  File "/Users/hannahbish/Dropbox/BHB_MCMC/Hannah_test/model_lineprofile.py", line 69, in model_lineprofile
    taured0 = N * 1.497e-15 * transinfo['lamfred0'] / bD#['value']
  File "/Users/hannahbish/anaconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 1080, in __div__
    return self.__truediv__(other)
  File "/Users/hannahbish/anaconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 1059, in __truediv__
    return super(Quantity, self).__truediv__(other)
TypeError: unsupported operand type(s) for /: 'float' and 'dict'

It was sometime in the last year or two when py_igmguesses got an update (I know, it got many) Hannah’s programs fully stopped being able to use the new output .json files. 
It looks like a units issue? I’m just not sure. Do you have any ideas for how she can modify her code to not get this error when reading in py_igmguesses output from current version? (The old output files still work with this set of MCMC codes). Let me know if you want to see the actual code or the json files in question-- but that might be brutal (there are 7 of them in total). I thought someone else might have run into something like this and have an easy fix! 

Thanks!

**Comment by profxj** [comment]
Well, the main thing to keep in mind is that JSON is a very strict format:

http://json.org/

When you load one in Python, it will be a dict with types
allowed by JSON (int, float, etc.).  So, if the items save
in our JSON files for `igm_guesses` has evolved just 
keep in mind the dict will contain only these simple items.

And react accordingly..  Not sure I can help much more.

**Comment by ntejos** [comment]
Indeed, this seems an error happening outside `pyigm`. According to the information it is a TypeError: `TypeError: unsupported operand type(s) for /: 'float' and 'dict'`. Thus the easiest way to solve it is to understand what variables are casing the discrepancy. There seems to be an incompatibility of variables in line 69 of `model_lineprofile.py`: ` taured0 = N * 1.497e-15 * transinfo['lamfred0'] / bD#['value']`. No idea what types are `transinfo`, `N`, or `bD`. I recommend to check if the types of these variables are the ones they are supposed to be. Sorry for not being of more help...
