### ISSUE TITLE
U button is unreliable

### ISSUE THREAD

**Issue by jessicawerk** [pyigm/pyigm#36]
It produces the following error across platforms for the most up-to-date version: 

Traceback (most recent call last):
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 313, in keyPressEvent
    FigureCanvasBase.key_press_event(self, key, guiEvent=event)
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 1847, in key_press_event
    self.callbacks.process(s, event)
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 563, in process
    proxy(_args, *_kwargs)
  File "/Users/jwerk/anaconda/lib/python2.7/site-packages/matplotlib/cbook.py", line 430, in **call**
    return mtd(_args, *_kwargs)
  File "/Users/jwerk/python/pyigm/pyigm/guis/igmguesses.py", line 888, in on_key
    self.parent.update_available_lines(linelist=self.llist['List'])
  File "/Users/jwerk/python/pyigm/pyigm/guis/igmguesses.py", line 270, in update_available_lines
    transitions = linelist.available_transitions(
AttributeError: 'unicode' object has no attribute 'available_transitions'

**Comment by profxj** [comment]
In which GUI?

**Comment by jessicawerk** [comment]
Oops. Sorry, thought I put in igmguesses specifically, sorry. pyigm_igmguesses.

**Comment by ntejos** [comment]
This should have been addressed in PR #37. Will close for now but @jessicawerk let me know if something is still odd and we will reopen this issue.
